services:
  postgres:
    image: postgres:18-alpine
    container_name: psgc_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: psgc_db
    ports:
      - "${POSTGRES_PORT:-5436}:5432"
    volumes:
      - psgc-postgres:/var/lib/postgresql/data
    networks:
      - psgc-network

  redis:
    image: redis:8.2.0-alpine
    container_name: psgc-redis
    ports:
      - "6379:6379"
    networks:
      - psgc-network
    volumes:
      - psgc-redis:/data

networks:
  psgc-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.0

volumes:
  psgc-postgres:
  psgc-redis:
